Feat/popover
gossip-ink/gossip pull request #32
Opened 2021-07-04 09:59 UTC by pearmini

# Popover

Add basic popover component. 

## Introduction

There are three ways to trigger popover: `click`, `hover` and `focus` and it can be placed on the `top/bottom/right/left` of the target element.

## Usage

```js
import { Popover } from 'components';

function Demo() {
  return (
    <Popover triggerAction="hover" content={<div>hello popover</div>}>
      <input />
    </Popover>
  )
}
```

## Notes

There are two main parts of popover: `trigger` and `portal`. Trigger is the part which react to user's input, so we should extend its props to handle supported events and measure its dimensions to place the popup. And portal is where we create the actual popup, so we should create and mount a container and pass the child to it.

2021-07-04 10:37 UTC, chengluyu commented
Nicely done! Here are the effects in current implementation.

* `placement="bottom"`
  
  <img width="383" alt="image" src="https://user-images.githubusercontent.com/2239547/124381585-d5620080-dcf5-11eb-9d9d-18fc8621983d.png">

* `placement="top"`

  <img width="256" alt="CleanShot 2021-07-04 at 18 32 55@2x" src="https://user-images.githubusercontent.com/2239547/124381667-46a1b380-dcf6-11eb-8fd5-de31e0da67de.png">

* `placeoment="left"`

  <img width="242" alt="CleanShot 2021-07-04 at 18 31 22@2x" src="https://user-images.githubusercontent.com/2239547/124381649-25d95e00-dcf6-11eb-8275-d1d41b7a88bf.png">

* `placement="right"`

  <img width="240" alt="CleanShot 2021-07-04 at 18 33 24@2x" src="https://user-images.githubusercontent.com/2239547/124381673-57eac000-dcf6-11eb-9e7c-2b7ea436c169.png">

Here are some possible improvements.

* Add a `gap` option specifying the distance to popover contents.
* Align the center of popover contents to the center of trigger elements.
* Add more placements: `{side}-{alignment}` where `side` is one of `top`, `right`, `bottom`, and `left`, and `alignment` is one of `start`, and `end`. See [Tippy.js documentation](https://atomiks.github.io/tippyjs/#placement) for previews.

2021-07-05 06:13 UTC, chengluyu requested changes

2021-07-05 06:13 UTC, chengluyu commented on src/components/Popover.tsx
> +  }
I think we can move these functions to the file scope because they don’t capture any local variables.

2021-07-05 06:13 UTC, chengluyu commented on src/components/Popover.tsx
> +  }
Missing return statements in the end of `shouldShowWhen`.

2021-07-05 06:13 UTC, chengluyu commented on src/components/Popover.tsx
> +  function fireEvents(type: string, event: TriggerEvent) {
Add function return type, please.

2021-07-05 06:13 UTC, chengluyu commented on src/components/Popover.tsx
> +  function onPopupVisible(visible: boolean) {
Add function return type, please.

2021-07-05 06:13 UTC, chengluyu commented on src/components/Popover.tsx
> +  function calculatePoint() {
Add function return type, please.

2021-07-05 06:13 UTC, chengluyu commented on src/components/Popover.tsx
> +  function getNewChildProps() {
Add function return type, please.

2021-07-05 06:13 UTC, chengluyu commented on src/hooks/useMeasure.ts
> +export default function () {
Add function name, please.

2021-07-05 14:13 UTC, pearmini commented on src/components/Popover.tsx
> +  function fireEvents(type: string, event: TriggerEvent) {
ok

2021-07-05 14:14 UTC, pearmini commented on src/components/Popover.tsx
> +  }
Sounds right.

2021-07-05 14:14 UTC, pearmini commented on src/components/Popover.tsx
> +  }
ok

2021-07-05 14:41 UTC, pearmini commented
Will you implement the new features mentioned above? @chengluyu

2021-07-05 14:43 UTC, pearmini commented
> > Will you implement the new features mentioned above? @chengluyu
> 
> Yes. But in new PRs.

Ok, If this PR is ok for you, then you can merge it.

2021-07-05 14:44 UTC, chengluyu commented
> > > Will you implement the new features mentioned above? @chengluyu
> 
> > 
> 
> > Yes. But in new PRs.
> 
> 
> 
> OK, If this PR is ok for you, then you can merge it.

Will do later.

2021-07-06 17:34 UTC, chengluyu approved these changes
Looks great.

2021-07-06 17:34 UTC, merged